# Generated by Django 2.1.5 on 2020-12-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinesetime',
            name='position',
            field=models.TextField(default='Your position is 56.4977 latitude, 84.9744 longitude. Your solarTIME is 10:07:52.66'),
        ),
        migrations.AlterField(
            model_name='chinesetime',
            name='answer',
            field=models.TextField(default='Now it is 寅 hour. The animal of the hour is tiger. This chinese hour lasts 3 and 4 astronomic hours.'),
        ),
    ]
