# Generated by Django 2.1.5 on 2021-02-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20201225_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChineseTime',
        ),
    ]
